### PR TITLE
docs: improve uml diagram

### PR DESCRIPTION
**Pull request by joseluis-teran-jalafund**
## Trello Ticket

**[ID-25](https://trello.com/c/5WwFjR36/34-id-25-improve-uml-diagram)**

## What did I do?

Update and refactor our UML diagram in services layers and enhance relationships between themselves.

## Why did I do this?

Due to we don't have a good management of services and good relationships between layers. Also, we weren't considering that we have duplicate functions and not resolving services functionality in a good way.

## How did I do it?

Create Requests and Responses classes for services according to each model. Refactor Services layer to remove duplicate functions in contracts and concretes and finally move the relationships inside of some packages to main file file.

## (Optional) Notes:

None.

### CODE REVIEW

**Review by alex-paca-jalafund — CHANGES_REQUESTED** [review]
Update image with last version of UML.

**Comment by joseluis-teran-jalafund** [comment]
> Update image with last version of UML.

Done.

**Review by alex-paca-jalafund — CHANGES_REQUESTED** [review]
There is an Interface that its not in use or related with other elements in the same package or others and its a factory interface for services,

**Review by alex-paca-jalafund — COMMENTED** [review]
Please if can explain why there is an interface on services that doesnt has relation with other class or abstract class, maybe its an missunderstanding or finger error

**Comment by joseluis-teran-jalafund** [comment]
> Please if can explain why there is an interface on services that doesnt has relation with other class or abstract class, maybe its an missunderstanding or finger error

I don't know if you remember but I told you on classes that I didn't remove it due to it was a part of Gabriela's work.

**Comment by joseluis-teran-jalafund** [comment]
But I'll review it again and I make some changes about it.

**Comment by gabriela-garcia-jalafund** [comment]
@joseluis-teran-jalafund 

1. There is a typographical error in the Delele method in IBaseRepository. It should be Delete.
2. The IBudgetObserver interface is defined but not used in the Business Logic Layer diagrams, as well as other classes, or their relationships are missing, such as Budget or Goal. Due to time constraints, I have no further observations.

**Comment by gabriela-garcia-jalafund** [comment]
@joseluis-teran-jalafund 

Also instead of T, why not a Guid for the id.
 Task<T> GetById(Guid id);
 Task<bool> Delete(Guid id);

image

**Comment by gabriela-garcia-jalafund** [comment]
@joseluis-teran-jalafund 

Be careful how you are naming, I mean databasesStrategy and the relationship is IDbConnectionFactory, as it could confuse what is being applied to strategy or factory. Be careful with that.

Screenshot from 2024-09-23 09-54-16

**Comment by joseluis-teran-jalafund** [comment]
> @joseluis-teran-jalafund
> 
> 1. There is a typographical error in the Delele method in IBaseRepository. It should be Delete.
> 2. The IBudgetObserver interface is defined but not used in the Business Logic Layer diagrams, as well as other classes, or their relationships are missing, such as Budget or Goal. Due to time constraints, I have no further observations.

About IBugdetObserver I didn't really consider at all. I maintained for 3rd phase. I could work on it, but I suggest to move on and then we can come back to complete it. What do you think?

**Comment by joseluis-teran-jalafund** [comment]
> @joseluis-teran-jalafund
> 
> Be careful how you are naming, I mean databasesStrategy and the relationship is IDbConnectionFactory, as it could confuse what is being applied to strategy or factory. Be careful with that.
> 
> Screenshot from 2024-09-23 09-54-16

Yeah, you're right! I forgot to update those names with the latest version of layer data. But now it's update it.

**Comment by GabyGV-GGV** [comment]
@joseluis-teran-jalafund In my case, I have no further observations. Good job!

**Review by GabyGV-GGV — APPROVED** [review]

**Review by gabriela-garcia-jalafund — APPROVED** [review]

**Review by alex-paca-jalafund — APPROVED** [review]
Nice work

**Pull request merged**
