### PR TITLE
fix: set tablename_id in update

### PR DESCRIPTION
**Pull request by gabriela-garcia-jalafund**
## Trello Ticket

[ID-32](https://trello.com/c/3Shnm4E6/43-id-32-resolve-update-in-repository)

---
## What did I do?

I fixed a bug in the BaseRepository<T> class that affected the Update method when updating records in the database. Specifically, the WHERE clause was not correctly handling the ID field, as it used @Id instead of referencing the proper column name ({tableName}_id). I updated the query to dynamically reference the correct table and field names to ensure the update operation works as expected.

## Why did I do this?
This fix was necessary because the Update method was failing when trying to match records by ID. The generated SQL query was not correctly identifying the primary key field due to improper formatting, which resulted in no records being updated. By resolving this issue, I ensure that updates can be properly applied to any entity in the database.

## How did I do it?

I modified the Update method by changing the WHERE clause to use the correct ID field dynamically for each entity. Specifically, I used StringUtils.ToSnakeCase(typeof(T).Name) to properly format the table and column names, ensuring the query accurately reflects the primary key structure in the database. This fix was implemented using Dapper to maintain consistency in how we interact with the database.

### CODE REVIEW

**Comment by gabriela-garcia-jalafund** [comment]
[ID-32: Resolve update in Repository](https://trello.com/c/3Shnm4E6/43-id-32-resolve-update-in-repository)

**Review by alex-paca-jalafund — CHANGES_REQUESTED** [review]
Fix its not working, im using the information below and its not updating the information of the income.

In order to test i use the code on the PR of Income Controller, but updating its exiting with code 0 column "id" doesnt exists.


Screenshot from 2024-09-29 10-05-06

**Review by alex-paca-jalafund — CHANGES_REQUESTED** [review]
The solution still doesnt working. Now it seems like there is no giving an error but also its not updating the information on the DB.

There are no comments on dotnet run terminal or docker compose terminal, just says exit code 0 in the update result. please check if it works before.
Screenshot from 2024-09-29 19-05-54

**Review by alex-paca-jalafund — APPROVED** [review]
Update working correctly for both repositories Income and Expenses

**Review by joseluis-teran-jalafund — APPROVED** [review]

**Pull request merged**
