### PR TITLE
refactor: add attributes to entities according to the UML

### PR DESCRIPTION
**Pull request by salet-gutierrez-jalafund**
## Trello Ticket

[ID-23](https://trello.com/c/xPGA4Itm)

## What did I do?

All the necessary entities were implemented according to the established UML.

## Why did I do this?

I did it so that you can see what entities we will have in our program.

## How did I do it?

I had to see the entities in the UML, which is the following:

image

According to the UML, I created the entities in the classes already created.

### CODE REVIEW

**Review by alex-paca-jalafund — COMMENTED** [review]
Unique observation, there is no implementation its an refactor, please change the PR message "feat: implement entity classes"according with the changes on the code.

**Review by alex-paca-jalafund — APPROVED** [review]
Nice work.

**Comment by joseluis-teran-jalafund** [comment]
@salet-gutierrez-jalafund it looks good but take into account the following for future work.

When committing changes, it's important to group related updates together in a single commit, rather than committing each file individually. If the new code or refactor is logically related such as implementing a new feature, fixing a bug, or restructuring a particular module it's best to bundle those changes into one commit. This practice helps maintain a clear and concise project history.

**Comment by gabriela-garcia-jalafund** [comment]
Good job with the entities!

**Review by gabriela-garcia-jalafund — APPROVED** [review]

**Pull request merged**
